app = "csui-csge602022-tutorial"

[build]
  dockerfile = "Dockerfile"

  [[build.args]]
    NODE_ENV_ARG = "production"
    DOCKER_ARG = "true"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
