# Reminder: Create the app and initialise fly.toml via flyctl launch.
# Unlike Heroku, an app on Fly.io needs to be created first before any
# codebase can be built and deployed as that particular app.
app = "csui-csge602022-tutorial"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
